### ISSUE TITLE
Using the dataset

### ISSUE THREAD

**Issue by zas97** [AlexanderKroll/ESP#1]
Hello,

I want to train my own model in this dataset, I would like to know where can I find the dataframe containing all the data with this 3 columns: "smiles", "protein_sequence", "score (0 or 1 depending if it catalyzes or not)".

Thank you and let me congratulate you for your great work

**Comment by AlexanderKroll** [comment]
Hi Joan, 

in the folder /data/splits/ you can find the files "df_train_with_ESM1b_ts_GNN.pkl", "df_test_with_ESM1b_ts_GNN.pkl". These files contain the columns "Uniprot ID", "molecule ID", and "Binding" (score that is 0 or 1). You can use the dataframe located at "data/enzyme_data/UNIPROT_df.pkl" to map the UniProt ID to the amino acid sequences. The molecule IDs are either CHEBI ID or KEGG IDs (starting with a "C" or "D"). You can probably use these IDs to map to SMILES strings. Let me know if you need some help with that.

**Comment by zas97** [comment]
Thank you, I can manage from here =)
