### ISSUE TITLE
Assistance Request for Creating 'all_sequences_esm1b_ts_mean.pt

### ISSUE THREAD

**Issue by atabaigi** [AlexanderKroll/ESP#10]
Dear Authors 
 I hope that you are doing well.
 I have calculated  `ESM1b_ts` and `ESM1b` vectors . in next setp I want to create `all_sequences_esm1b_ts_mean.pt`, However, I am uncertain about the steps involved in this process.

Could you kindly provide guidance on how to proceed with this task?

Your assistance is greatly appreciated.

Best regards,
Vahid

**Comment by AlexanderKroll** [comment]
Dear Vahid, 

I uploaded the python file "training_ESM1b_taskspecific_mean.py" to the folder "notebooks_and_code". It can be executed in the same way as the "training_ESM1b_taskspecific.py" to train the task-specific ESM-1b model. Does this answer your question?

Please note that the model ts_mean model is not very important for the overall process as it results in comparable but slightly worse results compared to the ESM-1b_ts model with classification token.

Best,
Alex
