### ISSUE TITLE
Missing command for training task specific ESM1b model

### ISSUE THREAD

**Issue by maxall41** [AlexanderKroll/ESP#12]
It seems that the command used to train the task specific ESM1b model is missing from the "1_0 - Creating enzyme-substrate database from GOA database.ipynb" notebook (See below screenshot)

<img width="1027" alt="Screenshot 2023-12-02 at 4 31 07 PM" src="https://github.com/AlexanderKroll/ESP/assets/41460735/5a11ab2c-6650-4f43-8a3b-a5c80defae17">

Could you provide this command?

Thanks,
Max

**Comment by AlexanderKroll** [comment]
Dear Max, 

sorry for that missing line. It is 
````
python training_ESM1b_taskspecific.py 
````

I added it to the notebook. Thanks for pointing it out.

Best,
Alex
