### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by Biologicalbigdata** [AlexanderKroll/ESP#16]
Dear Authors,
would you please provide the missing files:
mol_folder = "C:\\Users\\alexk\\mol-files\\"
mol = Chem.MolFromMolFile(mol_folder +  "mol-files\\" + met_ID + '.mol')

Best,
Steve

**Comment by AlexanderKroll** [comment]
Dear Steve,

As you can see on the readme page of this repository, you need to download an additional data folder from zenodo (link is provided in the readme). Inside this folder you have a subfolder called mol_files, which is the folder you need. And then you have to change the path specified in the "mol_folder" variable. Let me know if anything is unclear.

Best,
Alex
