### ISSUE TITLE
Inquiry Data Files

### ISSUE THREAD

**Issue by toooooodo** [AlexanderKroll/ESP#19]
Dear Alex,

Thanks for sharing this exceptional work. I noticed that there are a lot of files in the data folder, and I was wondering if there are organized data files for the substrate `SMILES` and protein `FASTA` pairs used in the paper. Based on my understanding, the dataset should consist of substrate and enzyme pairs. If such organized files are available, it would greatly aid in my research efforts.

In the event that these files are not currently included, I would greatly appreciate any guidance or direction you could provide on how to obtain them.

Thank you very much for your time and assistance.

**Comment by AlexanderKroll** [comment]
Hi, 

I uploaded two additional datasets (training and test datasets) with the SMILES strings for the small molecules and the protein amino acid sequence for the proteins here: https://zenodo.org/records/10977950

I hope this is what you need.

Best,
Alex
