### ISSUE TITLE
How to do inference on new data points

### ISSUE THREAD

**Issue by zas97** [AlexanderKroll/ESP#2]
How do you do inference given a new sequence and a smiles molecule?

**Comment by AlexanderKroll** [comment]
Hi zas97,

sorry for my late response. If you want to make predictions for a new enzyme-small molecule pair, you can for example use our web server: https://esp.cs.hhu.de/ES_pred_single . If you want to make predictions using a python function, I can upload easy usable python functions to a GitHub repository for you.

**Comment by zas97** [comment]
Yes please, I would appreciate it

**Comment by AlexanderKroll** [comment]
Here is the repository containing only the ESP prediction function: https://github.com/AlexanderKroll/ESP_prediction_function
