### ISSUE TITLE
dear author can you tell me what should be placed in datasets_PubChem and mol_folder

### ISSUE THREAD

**Issue by mintuos** [AlexanderKroll/ESP#3]
Dear AlexanderKroll,

I am a user of your code and I have come across two paths while using it:
in ESP/notebooks_and_code/additional_code/data_preprocessing.py

Lines 14 and 15
datasets_PubChem = "D:\\projects_deutschland\\Prediction_of_KM_V3\\datasets\\substrate_synonyms"
mol_folder = "C:\\Users\\alexk\\mol-files\\"

Could you please let me know what files should be placed in these paths? I am trying to run your code and I want to ensure that I have put the files in the correct location for the code to run properly.

Thank you for your help!

Best regards

**Comment by AlexanderKroll** [comment]
Dear mintuos,

I am sorry for this error. I uploaded an additional folder to zenodo (https://doi.org/10.5281/zenodo.8016269) with the missing files and I adjusted the specified paths in line 14 and 15. You should download the additional folder from zenodo, unzip it and place it where the "notebooks_and_code" and "data" folder of this repository is (see also the Readme of this repository). I hope you are now able to run the code.

Best,
Alex
