### ISSUE TITLE
 Questions about raining gradient boosting models

### ISSUE THREAD

**Issue by mh8859** [AlexanderKroll/ESP#6]
Dear author：
Hello，
I read the article code you provided, but I see that the model name you are using on the ESP prediction code is "xgboost_model_production_mode_gnn_esm1b_ts.dat".
Your code in jupyter doesn't save this model, you only save the model named "xgboost_model_production_mode.dat".
Moreover, I trained the xgboost model in your jupyter file, the shape of the data is (n, 1280+50), and in the prediction program, the dimension of each data is (n, 1280+100), what is the problem? 
Looking forward to your reply.

**Comment by AlexanderKroll** [comment]
Dear mh8859,

I apologize for my late response. You are correct in noting that the dimension of the substrate representation in the GitHub repository "ESP_prediction_function" is 100 instead of 50. This discrepancy should indeed be in agreement with our paper and this repository, where we used a dimension of 50. However, our tests have shown that this dimensional difference has a minimal impact on model performance. Therefore, the prediction results should not be affected. 
Regardless, I plan to update the substrate representation dimension in the "ESP_prediction_function" repository to 50 in the near future to ensure consistency. Thank you for bringing this to my attention, and I apologize for any confusion this may have caused.

**Comment by mh8859** [comment]
> 

Very grateful feedback. I have another problem, in the "training_ESM1b_taskspecific.py" document again, the number of the esm1b model used in the training is based on "Uniprot ID" and "Sequence". Use "Uniprot ID", but use "KEGG", "InChI" or "SMILES"?

**Comment by mh8859** [comment]
> Dear mh8859,
> 
> I apologize for my late response. You are correct in noting that the dimension of the substrate representation in the GitHub repository "ESP_prediction_function" is 100 instead of 50. This discrepancy should indeed be in agreement with our paper and this repository, where we used a dimension of 50. However, our tests have shown that this dimensional difference has a minimal impact on model performance. Therefore, the prediction results should not be affected. Regardless, I plan to update the substrate representation dimension in the "ESP_prediction_function" repository to 50 in the near future to ensure consistency. Thank you for bringing this to my attention, and I apologize for any confusion this may have caused.

Very grateful feedback. I have another problem, in the "training_ESM1b_taskspecific.py" document again, the number of the esm1b model used in the training is based on "Uniprot ID" and "Sequence". Use "Uniprot ID", but use "KEGG", "InChI" or "SMILES"?

**Comment by mh8859** [comment]
> Dear mh8859,
> 
> I apologize for my late response. You are correct in noting that the dimension of the substrate representation in the GitHub repository "ESP_prediction_function" is 100 instead of 50. This discrepancy should indeed be in agreement with our paper and this repository, where we used a dimension of 50. However, our tests have shown that this dimensional difference has a minimal impact on model performance. Therefore, the prediction results should not be affected. Regardless, I plan to update the substrate representation dimension in the "ESP_prediction_function" repository to 50 in the near future to ensure consistency. Thank you for bringing this to my attention, and I apologize for any confusion this may have caused.

Thank you very much for your reply.  I have another question. In your "training_ESM1b_taskspecific.py" file, the trained esm1b model uses the data set to predict "Binding" based on "Uniprot ID" and "Sequence".  But why not use "Uniprot ID" in ESP_prediction_function instead of "KEGG", "InChI" or "SMILES"?

**Comment by AlexanderKroll** [comment]
I am not sure if I fully understand your question. In "training_ESM1b_taskspecific.py" we use "Sequence" (protein amino acid sequence) as the input for the ESM-1b model and later add a representation for the small molecule (which was previously derived from a KEGG ID, InChI string or SMILES string. We only use the UniProt ID to store an identifier for the protein. 
In "ESP_prediction_function", we use the amino acid sequence together with the KEGG ID, InChI string or SMILES string as the input for the model.
