### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by atabaigi** [AlexanderKroll/ESP#8]
Hello Dear Authors,
I want to reproduce the results in PyCharm
After downloading and placing all files as it shown in picture
-
![Screenshot 2023-08-21 at 11 58 29](https://github.com/AlexanderKroll/ESP/assets/103953780/abaec9aa-e392-40bf-8c3f-9ad524a70893)

I am having an issue with louding ```df_UID_MID.pkl``` file  in data_preprocessing 
.py
-
```python
df_UID_MID = pd.read_pickle(join(CURRENT_DIR, ".." ,"data", "enzyme_substrate_data", "df_UID_MID.pkl"))
```
Output :
-
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vahidatabaigi/PycharmProjects/ESP-main/notebooks_and_code/additional_code/data_preprocessing.py", line 17, in <module>
    df_UID_MID = pd.read_pickle(join(CURRENT_DIR, ".." ,"data", "enzyme_substrate_data", "df_UID_MID.pkl"))
  File "/Users/vahidatabaigi/anaconda3/envs/ESP-Main/lib/python3.8/site-packages/pandas/io/pickle.py", line 196, in read_pickle
    with get_handle(
  File "/Users/vahidatabaigi/anaconda3/envs/ESP-Main/lib/python3.8/site-packages/pandas/io/common.py", line 710, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vahidatabaigi/PycharmProjects/ESP-main/notebooks_and_code/additional_code/../data/enzyme_substrate_data/df_UID_MID.pkl'
```
However, as indicated in the picture, the file exists and the directory is accurate. I considered the possibility that the issue might be with the ```join()``` function. To address this error, I resolved it by directly pasting the path to ```df_UID_MID.pkl``` within ```pd.read_pickle()```, removing the use of the ```join()``` function.
-
```python
df_UID_MID = pd.read_pickle("/Users/vahidatabaigi/PycharmProjects/ESP-main/data/enzyme_substrate_data/df_UID_MID.pkl")
```
output:
-
```output
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vahidatabaigi/PycharmProjects/ESP-main/notebooks_and_code/additional_code/data_preprocessing.py", line 18, in <module>
    df_UID_MID = pd.read_pickle("/Users/vahidatabaigi/PycharmProjects/ESP-main/data/enzyme_substrate_data/df_UID_MID.pkl")
  File "/Users/vahidatabaigi/anaconda3/envs/ESP-Main/lib/python3.8/site-packages/pandas/io/pickle.py", line 217, in read_pickle
    return pickle.load(handles.handle)  # type: ignore[arg-type]
_pickle.UnpicklingError: invalid load key, 'v'.
```

I am using mac M1 machine and I created a sepretated conda env and installed the follwoing packages, some of the required packages  with certain version i wasnot able to install becuase of conflict. To resolve this, I incrementally adjusted the versions, seeking a compatible version.
-
```
(ESP-Main) vahidatabaigi@********** % conda list
# packages in environment at /Users/vahidatabaigi/anaconda3/envs/ESP-Main:
#
# Name                    Version                   Build  Channel
biopython                 1.81             py38hb991d35_0    conda-forge    
.
.
. 
jupyter                   1.0.0            py38hca03da5_8  
jupyter_client            7.4.9            py38hca03da5_0  
jupyter_console           6.6.3            py38hca03da5_0  
jupyter_core              5.3.0            py38hca03da5_0  
jupyter_events            0.6.3            py38hca03da5_0  
jupyter_server            1.23.4           py38hca03da5_0  
jupyter_server_fileid     0.9.0            py38hca03da5_0  
jupyter_server_ydoc       0.8.0            py38hca03da5_1  
jupyter_ydoc              0.2.4            py38hca03da5_0  
jupyterlab                3.6.3            py38hca03da5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.22.0           py38hca03da5_0  
jupyterlab_widgets        3.0.5            py38hca03da5_0  
numpy                     1.21.2           py38hb38b75b_0  
numpy-base                1.21.2           py38h6269429_0  
pandas                    1.3.0            py38h3777fb4_0    conda-forge
.
.
.
python                    3.8.12          hd949e87_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py38hca03da5_0  
python-json-logger        2.0.7            py38hca03da5_0  
python_abi                3.8                      2_cp38    conda-forge
pytorch                   2.0.1                   py3.8_0    pytorch
.
.
.
rdkit                     2021.03.3        py38hbcbf861_0    conda-forge
.
.
.


```
I am looking forward to your reply.
Thank you
Vahid

**Comment by Old-Shatterhand** [comment]
Hi,

for me, the trick was to install python 3.7.7 (@atabaigi you installed python 3.8.12) and pandas 1.3.0 (tested on a Linux machine). Then
```
import pandas as pd

df = pd.read_pickle("path/to/df_UID_MID.pkl")
```
works fine. `pickle.load(open("path/to/df_UID_MID.pkl", "r"))` does not work, but that's a different story (some version incompatibilities and pandas behavior, I can't find the StackOverflow post for that at the moment).

I'd consider this issue resolved if @atabaigi confirms.

Best, Roman

**Comment by fmoorhof** [comment]
Sorry for re-opening,
i also stumbled across the error and found it not entirely explained. To my understanding are pointing these `.pkl` files to an online ressource. So you can not read them directly but need to get the file from the online resource first. This can be done by pulling the repository with `git lfs pull`. You can install `lfs` [from here](https://git-lfs.com/).

**Comment by zhenjiagan** [comment]
> Sorry for re-opening, i also stumbled across the error and found it not entirely explained. To my understanding are pointing these `.pkl` files to an online ressource. So you can not read them directly but need to get the file from the online resource first. This can be done by pulling the repository with `git lfs pull`. You can install `lfs` [from here](https://git-lfs.com/).

Hello,

I ran into issue #26 when using git lfs pull to fetch all .pkl files, and I’ve created a GitHub issue to document the problem. Have you experienced similar issues, and if so, how did you address them?
